package:
  name: cetcolors
  version: 0.9.0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest >=2.8.5
  imports:
    - cetcolors

about:
  home: https://github.com/bokeh/cetcolors
  license: CC-BY
