package:
  name: colorcet
  version: 1.0.0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest >=2.8.5
  imports:
    - colorcet

about:
  home: https://github.com/bokeh/colorcet
  license: CC-BY
